project:
  type: website
  output-dir: docs

website:
  title: "Nicolas Laub-Sabater"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: "AI Detectors"
           href: tt2.html
         - text: "Olympics"
           href: Olympics.html
         - text: "Obama Tweets"
           href: Obama.html
         - text: "Will I ever get a single?? Simulation"
           href: simulationproject.html
         - text: "Ethical Dilemma"
           href: ethical.html
         - text: "Is this actually a down year for PP Baseball?"
           href: Final6.html

      

        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

