project:
  type: website
  output-dir: docs

website:
  title: "Nicolas Laub-Sabater"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: "The Effectiveness of AI Detectors"
           href: tt2.html
         - text: "Olympics: height and weight relationships"
           href: Olympics.html
         - text: "Obama's Tweets"
           href: Obama.html
#         - text: "Will I ever get a single?? Simulation"
#           href: simulationproject.html
         - text: "The Ethics of Data Science"
           href: ethical.html
         - text: "Different Policing Across the Bay Bridge?"
           href: SQL.html           
         - text: "Is this actually a down year for PP Baseball?"
           href: Final6.html
         - text: "Presentation of Additions to Website"
           href: Presentation.html 
         - text: "Resume"
           href: Resume.html 
      

        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

