project:
  type: website
  output-dir: docs

website:
  title: "Nicolas Laub-Sabater"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: "AI Detectors"
           href: tt2.html
         - text: "Olympics"
           href: olympics.html
         

      

        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

